### ISSUE TITLE
Supported architectures

### ISSUE THREAD

**Issue by alcir** [AlizaMedicalImaging/AlizaMS#2] opened 2021-09-21 17:04 UTC
Hello.
I was trying to package alizams on Fedora.
It compiles successfully on x86_64, while it fails on all other architectures (armv7, aarch64, ppc64le, s390x).

At a first glance, the compilation error is here: 
```
fatal error: xmmintrin.h: No such file or directory
   34 | #include <xmmintrin.h>
```

Packagers more experienced than me stated that xmmintrin.h is an header for SSE CPU instructions. SSE is an x86_64 extension.
So the solution could be to "wrap" such includes with
```
#ifdef __SSE__
#include <xmmintrin.h>
#endif
```

But the point is: does alizams is supposed to work on architectures other than x86_64?

Thanks.

**Comment by issakomi** [comment] 2021-09-21 18:21
Hello,

thank you.

I am not sure about these architectures, they are not tested, never tried, the issue with SSE may be solved with define DISABLE_SIMDMATH.

May be the line can be improved:
https://github.com/AlizaMedicalImaging/AlizaMS/blob/a0cafda32e4c591174e3833428a8ea04a035a21c/CMakeLists.txt#L855


BTW, macOS Apple Silicon M1 arm64 works well, but i have done some changes to get it working.

Are arm7 and aarch64 using OpenGL or OpenGLES? 

Is is possible to release only x86_64 / x86?

**Comment by alcir** [comment] 2021-09-21 19:03
Thank you for your prompt reply.

> I am not sure about these architectures, they are not tested, never tried, the issue with SSE may be solved with define DISABLE_SIMDMATH.

I will take a look.

> Are arm7 and aarch64 using OpenGL or OpenGLES?

As far as I've seen in another compilation error on aarch64, by switching an "if arm" statement to OpenGL that error has gone. So I think that OpenGL is used.

> Is is possible to release only x86_64 / x86?

Yes. I think that I will end up doing that. (My competencies in programming languages are very limited).

**Comment by issakomi** [comment] 2021-09-22 06:25
> > Is is possible to release only x86_64 / x86?

> Yes. I think that I will end up doing that.

I think it is better now. SSE2 issue is very easy to fix, but i am a little lost about Qt / OpenGL, maybe i shall buy RPi later and try.

There is another point. I have seen that Fedora uses Wayland by default, there are many problems with Qt's Wayland QPA. Debian/Ubuntu also uses Wayland by default now, but for Qt apps _QPA Wayland_ is not used, only if variable `QT_QPA_PLATFORM=wayland` is set, by default they use `xcb`.  On Fedora it is different, it is the reason i still release  [Aliza](https://www.aliza-dicom-viewer.com/download/download_aliza) _rpm_ only with Qt4. Qt5 build works on Fedora without problems with `QT_QPA_PLATFORM=xcb`, otherwise there is strange issue with transparency and many common Qt's Wayland warnings. It is safe to build with Qt4, even if AlizaMS can be build with Qt5 and Qt6. Qt4 is still available on Fedora 34. I have tried to find a workaround for transparency issue, but without success. i don't think there is a bug on my side, not 100% sure, but i use Qt5 with X11 myself many years with Debian, release Windows version with Qt5, macOS with Qt6 (to support arm64 M1 CPU). No problems, only with Qt's Wayland QPA. If you decide to use Qt4, there is also the cmake option  _USE_SYSTEM_GLEW_QT4_, to switch between included (default) GLEW (statically linked) and distribution's GLEW (dynamically linked). For Qt5/Qt6 builds GLEW is not used at all.

Kind regards

**Comment by issakomi** [comment] 2021-09-22 09:07
Maybe i have found simple workaround to force `xcb` platform and avoid QtWayland issues by setting (overriding) the environment variable at the beginning of main function
`setenv("QT_QPA_PLATFORM", "xcb", 1);`
Seem to work, but i have to test a little to be sure.

**Comment by alcir** [comment] 2021-09-22 09:25
> Maybe i have found simple workaround to force `xcb` platform and avoid QtWayland issues by setting (overriding) the environment variable at the beginning of main function
> `setenv("QT_QPA_PLATFORM", "xcb", 1);`
> Seem to work, but i have to test a little to be sure.

But it is at compile time?
Because I remember that before starting an application there was an environment variable to force... Well right now I don't remember. But such variable had something to do with QT and wayland.

**Comment by alcir** [comment] 2021-09-22 09:28
> I think it is better now. SSE2 issue is very easy to fix, but i am a little lost about Qt / OpenGL, maybe i shall buy RPi later and try.

Don't bother with that.  Having an application that supports x86_64 only is perfectly fine.

**Comment by issakomi** [comment] 2021-09-22 09:54
> But it is at compile time?

Yes

> And you can add it to the .desktop file.

Good  idea, it can be Qt argument "-platform" too, the as variable QT_QPA_PLATFORM, AFAIK. But seems to work with now with _setenv_. Already in master branch.

**Comment by alcir** [comment] 2021-09-22 10:47
> Good idea, it can be Qt argument "-platform" too, the same as variable QT_QPA_PLATFORM, AFAIK. But seems to work now with _setenv_. Already in master branch. So Qt4 can be avoided, i hope.

Thanks. I will try as soon as possible.

**Comment by issakomi** [comment] 2021-09-23 21:11
Thank you very much! Please kindly allow me several days to release next version. I am reviewing CMakeLists file and several other things. It would be really nice if there will be Fedora package. BTW, Qt6 is also possible, already works.

**Comment by alcir** [comment] 2021-09-26 07:42
> i have done some changes to avoid SSE2 issue, can not test, but there is also new cmake option `USE_FORCE_DISABLE_SIMDMATH` (_off_ by default).

OK. I can confirm that now it builds successfully on armv7 and aarch64.
I need to see if the compiled program actually runs. Maybe tomorrow.

**Comment by issakomi** [comment] 2021-09-26 10:30
> OK. I can confirm that now it builds successfully on armv7 and aarch64.
> I need to see if the compiled program actually runs. Maybe tomorrow.
Oh, thank you!
Interesting. I can imagine, not sure, that on _arm_ OpenGL _Core_ profile might work better. For Qt6 build i [set _Core_ profile](https://github.com/AlizaMedicalImaging/AlizaMS/blob/144bedc8cdb6b10da17941808742d3ca6d890b57/CMakeLists.txt#L868) (i use Qt6 only with macOS currently and macOS supports only _Core_ profile for OpenGL 3+). For Qt5 i don't set anything explicit, it ends up in _Compatibility_ profile  (might be better for older systems), maybe i shall add a cmake option to use Core profile with Qt5.

**Comment by issakomi** [comment] 2021-09-26 18:13
I have updated _CMakeLists.txt_, put options together for [better readability,](https://github.com/AlizaMedicalImaging/AlizaMS/blob/5b43d32c9a4020098c53f12554491a8d74ad0040/CMakeLists.txt#L62) renamed several options to follow convention, they start now with _ALIZA__ or _MDCM__ (cmake-gui and cache file sort variables by name). _MDCM__ were already correct, not changed.
Also added _ALIZA_QT5_COREGL_, _off_ by default(`-DALIZA_QT5_COREGL:BOOL=ON` to use Core profile for Qt5 build, may be required for _arm_).

Highly likely there is no need to change anything, default are still applicable, if you have used force-disable SSE/SSE2 (maybe it was required, not sure), the option is named _ALIZA_DISABLE_SIMDMATH_ now (`-DALIZA_DISABLE_SIMDMATH:BOOL=ON`).

If you use system libraries, they didn't change, e.g.
```
 -DALIZA_QT_VERSION:STRING=5 \
 -DCMAKE_SKIP_RPATH:BOOL=ON \
 -DMDCM_USE_SYSTEM_UUID:BOOL=ON \
 -DMDCM_USE_SYSTEM_ZLIB:BOOL=ON \
 -DMDCM_USE_SYSTEM_OPENJPEG:BOOL=ON \
 -DMDCM_USE_SYSTEM_CHARLS:BOOL=ON
```
Do you prefer system's libraries? ITK too? Statically linked included libraries and ITK work well, but may be there is policy like on Debian to prefer system's shared libraries always.

I think new release is so far ready, will look a little more at it and publish soon.

Thank you very much!

**Comment by alcir** [comment] 2021-09-27 15:07
The compiled program works! Tested on aarch64 (Pinebook Pro).

The only issue is that the buttons are without icons. And some buttons are "invisible": the button sqare appears (without the icon) only when the mouse cursor moves on them.

**Comment by issakomi** [comment] 2021-09-28 11:54
Thank you!

> The only issue is that the buttons are without icons. 

Probably something is wrong with Qt plugin `iconengines/libqsvgicon.so` or Qt SVG library (_libQt5Svg.so.5_ or _libQt6Svg.so.6_)

**Comment by issakomi** [comment] 2021-09-28 19:13
I am thinking about the issue with icons on _arm_. May be something is wrong resources in general. Do you see the green logo in "About" widget? It is PNG, so if it is visible the problem is only with SVG.

![logo](https://user-images.githubusercontent.com/1494580/135150551-d9b1eea6-044d-4d4e-bbc3-3d495b9e606b.png)

**Comment by alcir** [comment] 2021-09-30 13:04
> Do you see the green logo in "About" widget?

Yes

**Comment by issakomi** [comment] 2021-10-01 22:15
I remember that i had the issue with empty icons once somehow. Don't remember exactly how. Usually it shouldn't happen, but may happen if Qt can not resolve path for plugins. I don't know does it make sense to work on the problem. It is possible to check _qt5-qtsvg_ / _qt6-qtsvg_ package, check output with export `QT_DEBUG_PLUGINS=1`, set `export QT_PLUGIN_PATH`.

Another possibility is that there is bug in _arm_ Qt build, but it is unlikely, not sure. Workaround would be to generate PNG icons and add an option to cmake to switch at compile time.

**Comment by issakomi** [comment] 2021-10-11 13:55
I have found spec for possible alizams Fedora package
```
%build
export ITK_DIR=%{_libdir}/cmake/InsightToolkit
%cmake -DCMAKE_BUILD_TYPE:STRING=Release -DALIZA_QT_VERSION:STRING=5 \
  -DMDCM_USE_SYSTEM_ZLIB:BOOL=ON -DMDCM_USE_SYSTEM_OPENJPEG:BOOL=ON \
  -DMDCM_USE_SYSTEM_CHARLS:BOOL=ON -DMDCM_USE_SYSTEM_UUID:BOOL=ON \
  -DUSE_FORCE_CXX14:BOOL=ON \
  -DLIBRARY_OUTPUT_PATH=../../../../../%{_vpath_builddir}/lib
%cmake_build
```
Just FYI, the option _USE_FORCE_CXX14_ doesn't exist in 1.7.0. It is highly likely not required (was a workaround to avoid warnings with Debian's ITK-4.12). If required, there is the option [_ALIZA_CXX_STANDARD_](https://github.com/AlizaMedicalImaging/AlizaMS/blob/a5bf98bedb86f7b0ae862a613dfe331d01bfb86a/CMakeLists.txt#L77), possible values _Not set_ (default), _11_, _14_, _17_, e.g. `-DALIZA_CXX_STANDARD:STRING=14`.

**Comment by issakomi** [comment] 2021-10-11 14:33
```
%files
%license LICENSE
%doc README.md
%{_bindir}/%{name}
%{_datadir}/applications/%{name}.desktop
%{_datadir}/metainfo/%{name}.appdata.xml
%{_datadir}/icons/hicolor/*/apps/%{name}.png
%{_datadir}/icons/hicolor/*/apps/%{name}.svg
%{_mandir}/man1/%{name}.1*
%{_libdir}/libmdcmjpeg8.so.%{so_ver}*
%{_libdir}/libmdcmjpeg12.so.%{so_ver}*
%{_libdir}/libmdcmjpeg16.so.%{so_ver}*
```
Files `libmdcmjpeg8.so libmdcmjpeg12.so libmdcmjpeg16.so` shouldn't exists, there are intermediate `.a` static libraries, they are linked with executable during build, no need to copy or package, there is no option to build them as shared. Just remove last 3 lines should be fine.

**Comment by alcir** [comment] 2021-10-15 08:35
> Or was cmake modified?

You can see what the `%cmake` macro actually expands to by issuing this command:
`rpm -E '%cmake'`

**Comment by issakomi** [comment] 2021-10-15 09:54
> You can see what the %cmake macro actually expands to by issuing this command

Thanks, yes, this forces `-DBUILD_SHARED_LIBS:BOOL=ON`. I shall look what could be done, ether suppress it for JPEG libs or do it proper. Not yet sure. 

```
  /usr/bin/cmake \
        -S "." \
        -B "x86_64-redhat-linux-gnu" \
        -DCMAKE_C_FLAGS_RELEASE:STRING="-DNDEBUG" \
        -DCMAKE_CXX_FLAGS_RELEASE:STRING="-DNDEBUG" \
        -DCMAKE_Fortran_FLAGS_RELEASE:STRING="-DNDEBUG" \
        -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON \
        -DCMAKE_INSTALL_DO_STRIP:BOOL=OFF \
        -DCMAKE_INSTALL_PREFIX:PATH=/usr \
        -DINCLUDE_INSTALL_DIR:PATH=/usr/include \
        -DLIB_INSTALL_DIR:PATH=/usr/lib64 \
        -DSYSCONF_INSTALL_DIR:PATH=/etc \
        -DSHARE_INSTALL_PREFIX:PATH=/usr/share \
%if "lib64" == "lib64" 
        -DLIB_SUFFIX=64 \
%endif 
        -DBUILD_SHARED_LIBS:BOOL=ON
```

**Comment by issakomi** [comment] 2021-10-15 10:09
> Maybe in the aarch64 image it is not installed by default, while in Workstation it is.

For some reason Fedora's _rpmbuild_ doesn't add qt5-qtsvg to requirements/dependencies, both on x86_64 and aarch64.

**Comment by issakomi** [comment] 2021-10-15 20:42
Highly likely the warning in the post above can be ignored. Seem to be a regression in GCC

[https://gcc.gnu.org/bugzilla/show_bug.cgi?id=92718](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=92718)

I can reproduce test code from the bug on Fedora 34.

**Comment by issakomi** [comment] 2021-10-19 13:29
Hello,

> Also there is a very minor issue with not existent path for demo data sets

FYI, I have added tiny data sets (129 KB uncompressed). This requires one line in `%files` section of _spec_ file.
https://github.com/AlizaMedicalImaging/AlizaMS/blob/2cb1aacb3f10b272ecaf14062e4b02bbe0d8d565/fedora-34/alizams.spec#L60

**Comment by issakomi** [comment] 2021-11-18 08:49
@alcir 
Related to discussion on Bugzilla, here is the file with 3rd party licenses
https://github.com/AlizaMedicalImaging/AlizaMS/blob/master/debian-10/copyright

**Comment by issakomi** [comment] 2021-11-19 07:03
I have commented on Bugzilla and will close this issue, it become long and difficult to read. Please open an issue if there are any questions.
Thank you again! I really appreciate your help.

P.S. BTW, there are maybe a very minor issue in _metadata.xml_ file, there are two images in one screenshot section, only the 2nd is visible. But it can be ignore.

**Closed by issakomi** 2021-11-19 07:03 UTC
